<!DOCTYPE html>
<html lang="es-es">
  <head>
    
    <meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="generator" content="Hugo 0.59.1 with theme Tranquilpeak 0.4.7-BETA">
<meta name="author" content="La Galería Hexagonal">
<meta name="keywords" content="hashtags, national strike, mapas, datos, análisis, maps, data, analysis">
<meta name="description" content="Una discusión de tweets publicados con tres hashtags populares durante el paro de octubre en Ecuador, y del inconveniente para recuperar esos datos hoy en día.">


<meta property="og:description" content="Una discusión de tweets publicados con tres hashtags populares durante el paro de octubre en Ecuador, y del inconveniente para recuperar esos datos hoy en día.">
<meta property="og:type" content="article">
<meta property="og:title" content="Sobre los Tweets en el Paro Nacional">
<meta name="twitter:title" content="Sobre los Tweets en el Paro Nacional">
<meta property="og:url" content="https://ruevko.github.io/hexagonal/post/2020/01/23-sobre-tweets-paro-nacional/">
<meta property="twitter:url" content="https://ruevko.github.io/hexagonal/post/2020/01/23-sobre-tweets-paro-nacional/">
<meta property="og:site_name" content="La Galería Hexagonal">
<meta property="og:description" content="Una discusión de tweets publicados con tres hashtags populares durante el paro de octubre en Ecuador, y del inconveniente para recuperar esos datos hoy en día.">
<meta name="twitter:description" content="Una discusión de tweets publicados con tres hashtags populares durante el paro de octubre en Ecuador, y del inconveniente para recuperar esos datos hoy en día.">
<meta property="og:locale" content="es-es">

  
    <meta property="article:published_time" content="2020-01-23T00:00:00">
  
  
    <meta property="article:modified_time" content="2020-01-23T00:00:00">
  
  
  
    
      <meta property="article:section" content="Twitter">
    
  
  
    
      <meta property="article:tag" content="hashtags">
    
      <meta property="article:tag" content="paro nacional">
    
  


<meta name="twitter:card" content="summary">











  <meta property="og:image" content="https://ruevko.github.io/hexagonal/logo.png">
  <meta property="twitter:image" content="https://ruevko.github.io/hexagonal/logo.png">


    <title>Sobre los Tweets en el Paro Nacional</title>

    <link rel="icon" href="../../../../favicon.ico">
    

    

    <link rel="canonical" href="https://ruevko.github.io/hexagonal/post/2020/01/23-sobre-tweets-paro-nacional/">

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.4/jquery.fancybox.min.css" integrity="sha256-vuXZ9LGmmwtjqFX1F+EKin1ThZMub58gKULUyf0qECk=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.4/helpers/jquery.fancybox-thumbs.min.css" integrity="sha256-SEa4XYAHihTcEP1f5gARTB2K26Uk8PsndQYHQC1f4jU=" crossorigin="anonymous" />
    
    
    <link rel="stylesheet" href="../../../../css/style-twzjdbqhmnnacqs0pwwdzcdbt8yhv8giawvjqjmyfoqnvazl0dalmnhdkvp7.min.css" />
    
    

    
      
    
    
  </head>

  <body>
    <div id="blog">
      <header id="header" data-behavior="4">
  <i id="btn-open-sidebar" class="fa fa-lg fa-bars"></i>
  <div class="header-title">
    <a class="header-title-link" href="../../../../">La Galería Hexagonal</a>
  </div>
  
</header>

      <nav id="sidebar" data-behavior="4">
  <div class="sidebar-container">
    
      <div class="sidebar-profile">
        <a href="../../../../#about">
          <img class="sidebar-profile-picture" src="https://ruevko.github.io/hexagonal/logo.png" alt="Foto de autor" />
        </a>
        <h4 class="sidebar-profile-name">La Galería Hexagonal</h4>

      </div>
    
    <ul class="sidebar-buttons">
      
  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="../../../../">
    
      <i class="sidebar-button-icon fa fa-lg fa-globe-americas"></i>
      
      <span class="sidebar-button-desc">Inicio</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="../../../../categories">
    
      <i class="sidebar-button-icon fa fa-lg fa-map-marked-alt"></i>
      
      <span class="sidebar-button-desc">Categorías</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="../../../../tags">
    
      <i class="sidebar-button-icon fa fa-lg fa-map-marker-alt"></i>
      
      <span class="sidebar-button-desc">Etiquetas</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="../../../../archives">
    
      <i class="sidebar-button-icon fa fa-lg fa-search-location"></i>
      
      <span class="sidebar-button-desc">Archivos</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="../../../../page">
    
      <i class="sidebar-button-icon fa fa-lg fa-compass"></i>
      
      <span class="sidebar-button-desc">Créditos</span>
    </a>
  </li>


    </ul>
    <ul class="sidebar-buttons">
      

    </ul>
    <ul class="sidebar-buttons">
      

    </ul>
  </div>
</nav>

      


      

      <div id="main" data-behavior="4"
        class="
               hasCoverMetaIn
               ">
        <article class="post" itemscope itemType="http://schema.org/BlogPosting">
          
          
            <div class="post-header main-content-wrap text-left">
  
    <h1 class="post-title" itemprop="headline">
      Sobre los Tweets en el Paro Nacional
    </h1>
  
  
  <div class="postShorten-meta post-meta">
    
      <time itemprop="datePublished" datetime="2020-01-23T00:00:00Z">
        
  
  
  
  
    23 de Enero de 2020
  

      </time>
    
    
  
  
    <span>en</span>
    
      <a class="category-link" href="../../../../categories/twitter">Twitter</a>
    
  

  </div>

</div>
          
          <div class="post-content markdown" itemprop="articleBody">
            <div class="main-content-wrap">
              
<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    background-color: #ffffff;
    color: #a0a0a0;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #a0a0a0;  padding-left: 4px; }
div.sourceCode
  { color: #1f1c1b; background-color: #ffffff; }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span. { color: #1f1c1b; } /* Normal */
code span.al { color: #bf0303; background-color: #f7e6e6; font-weight: bold; } /* Alert */
code span.an { color: #ca60ca; } /* Annotation */
code span.at { color: #0057ae; } /* Attribute */
code span.bn { color: #b08000; } /* BaseN */
code span.bu { color: #644a9b; font-weight: bold; } /* BuiltIn */
code span.cf { color: #1f1c1b; font-weight: bold; } /* ControlFlow */
code span.ch { color: #924c9d; } /* Char */
code span.cn { color: #aa5500; } /* Constant */
code span.co { color: #898887; } /* Comment */
code span.cv { color: #0095ff; } /* CommentVar */
code span.do { color: #607880; } /* Documentation */
code span.dt { color: #0057ae; } /* DataType */
code span.dv { color: #b08000; } /* DecVal */
code span.er { color: #bf0303; text-decoration: underline; } /* Error */
code span.ex { color: #0095ff; font-weight: bold; } /* Extension */
code span.fl { color: #b08000; } /* Float */
code span.fu { color: #644a9b; } /* Function */
code span.im { color: #ff5500; } /* Import */
code span.in { color: #b08000; } /* Information */
code span.kw { color: #1f1c1b; font-weight: bold; } /* Keyword */
code span.op { color: #1f1c1b; } /* Operator */
code span.ot { color: #006e28; } /* Other */
code span.pp { color: #006e28; } /* Preprocessor */
code span.re { color: #0057ae; background-color: #e0e9f8; } /* RegionMarker */
code span.sc { color: #3daee9; } /* SpecialChar */
code span.ss { color: #ff5500; } /* SpecialString */
code span.st { color: #bf0303; } /* String */
code span.va { color: #0057ae; } /* Variable */
code span.vs { color: #bf0303; } /* VerbatimString */
code span.wa { color: #bf0303; } /* Warning */
</style>


<p>Los últimos meses del año pasado presenciaron movilizaciones en algunos países del mundo, respondiendo a acciones gubernamentales de diversas índoles. En Ecuador, las protestas de octubre fueron detonadas por las medidas económicas anunciadas por la presidencia, con el propósito de cumplir una agenda acordada con el Fondo Monetario Internacional. El principal cambio consistía en terminar el subsidio de combustibles; como suele suceder con las medidas inmediatas, que no contemplan un cambio progresivo ni el desarrollo equitativo para todos, ciertos sectores -estudiantes, transportistas, agricultores, indígenas- hubiesen sido los más afectados. Tras un paro nacional que se extendió del 3 al 13 de octubre, las medidas económicas fueron retiradas. Para mayor información sobre las medidas, las acciones de los sectores vulnerados y las represalias del gobierno, se sugiere consultar las siguientes fuentes: <a href="https://wambra.ec/la-protesta-indigena-y-popular-que-levanto-a-ecuador/">Wambra</a>, <a href="http://www.pichinchacomunicaciones.com.ec/">Pichincha Comunicaciones</a><a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>, <a href="https://www.revistacrisis.com/coyuntura/apuntes-sobre-el-triunfo-popular-de-octubre/">Crisis</a> y <a href="https://conaie.org/2019/10/09/septimo-dia-de-movilizacion-nacional-del-movimiento-indigena/">CONAIE</a>.</p>
<p>El propósito de este post es demostrar cómo ejecuté un análisis con los <em>tweets</em> generados entre el 1 y el 10 de octubre, considerando tres <em>hashtags</em> populares durante el paro nacional en Ecuador. La premisa es que la elección de un <em>hashtag</em> expone la intención del usuario, de reportar los hechos acontecidos durante el paro o de desaprobar al mismo. Originalmente trabajé con el paquete <code>twitteR</code> el cual permite obtener <em>tweets</em> a través de la API gratuita de Twitter; no obstante, es necesario ejecutar previamente una función de autenticación<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a>.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1"><span class="kw">library</span>(twitteR)</a>
<a class="sourceLine" id="cb1-2" title="2"></a>
<a class="sourceLine" id="cb1-3" title="3"><span class="kw">setup_twitter_oauth</span>(<span class="st">&quot;tus&quot;</span>, <span class="st">&quot;claves&quot;</span>, <span class="st">&quot;de&quot;</span>, <span class="st">&quot;consumidor&quot;</span>)</a>
<a class="sourceLine" id="cb1-4" title="4"></a>
<a class="sourceLine" id="cb1-5" title="5">wambra =<span class="st"> </span><span class="kw">userTimeline</span>(<span class="st">&quot;wambraEc&quot;</span>, <span class="dv">100</span>, <span class="dt">sinceID =</span> <span class="dv">1212053690737135616</span>,</a>
<a class="sourceLine" id="cb1-6" title="6">                      <span class="dt">excludeReplies =</span> <span class="ot">FALSE</span>, <span class="dt">includeRts =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<p>En este ejemplo se han solicitado cien publicaciones de la cuenta del blog Wambra, incluyendo <em>replies</em> y <em>retweets</em>. Efectivamente el resultado es una lista de <em>tweets</em> con sus respectivos metadatos ocultos: <code>tail(wambra, 3)</code></p>
<pre><code>## [[1]]
## [1] &quot;wambraEc: #MuertesEnElParo\nAnte el silencio y la falta de respuesta de las autoridades, sus familias decidieron contar sus hi… https://t.co/b5zXi9cuR6&quot;
## 
## [[2]]
## [1] &quot;wambraEc: [ESPECIAL]\nSon 11 nombres, muy poco pronunciados en la historia del #ParoNacional #Ecuador\n\n¿Quiénes eran las perso… https://t.co/82jimxB9P0&quot;
## 
## [[3]]
## [1] &quot;wambraEc: [INTERNACIONAL]\n#Chiapas: “Necesitamos y merecemos vivir”, ese fue el mensaje de clausura en el segundo Encuentro I… https://t.co/JKgRBVaQ0R&quot;</code></pre>
<p>Si bien el paquete implementado ya posee una función que tabula los metadatos, preferí escribir mi propia función ajustada al análisis:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1"><span class="kw">library</span>(dplyr)</a>
<a class="sourceLine" id="cb3-2" title="2"><span class="kw">library</span>(purrr)</a>
<a class="sourceLine" id="cb3-3" title="3"></a>
<a class="sourceLine" id="cb3-4" title="4">user2na =<span class="st"> </span><span class="cf">function</span>(user) <span class="kw">ifelse</span>(<span class="kw">length</span>(user) <span class="op">==</span><span class="st"> </span><span class="dv">0</span>, <span class="ot">NA_character_</span>, <span class="kw">paste0</span>(<span class="st">&quot;@&quot;</span>, user))</a>
<a class="sourceLine" id="cb3-5" title="5"></a>
<a class="sourceLine" id="cb3-6" title="6">coor2na =<span class="st"> </span><span class="cf">function</span>(coor) <span class="kw">ifelse</span>(<span class="kw">length</span>(coor) <span class="op">==</span><span class="st"> </span><span class="dv">0</span>, <span class="ot">NA_real_</span>, <span class="kw">as.double</span>(coor))</a>
<a class="sourceLine" id="cb3-7" title="7"></a>
<a class="sourceLine" id="cb3-8" title="8">list2tbl =<span class="st"> </span><span class="cf">function</span>(twts_list, <span class="dt">time_zone =</span> <span class="st">&quot;UCT&quot;</span>) <span class="kw">tibble</span>(</a>
<a class="sourceLine" id="cb3-9" title="9">   <span class="dt">isrt =</span> <span class="kw">map_lgl</span>(twts_list, <span class="op">~</span>.<span class="op">$</span>isRetweet),</a>
<a class="sourceLine" id="cb3-10" title="10">   <span class="dt">rts  =</span> <span class="kw">map_dbl</span>(twts_list, <span class="op">~</span>.<span class="op">$</span>retweetCount),</a>
<a class="sourceLine" id="cb3-11" title="11">   <span class="dt">favs =</span> <span class="kw">map_dbl</span>(twts_list, <span class="op">~</span>.<span class="op">$</span>favoriteCount),</a>
<a class="sourceLine" id="cb3-12" title="12">   <span class="dt">time =</span> <span class="kw">map_dbl</span>(twts_list, <span class="op">~</span>.<span class="op">$</span>created) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb3-13" title="13"><span class="st">      </span><span class="kw">as.POSIXct</span>(<span class="dt">tz =</span> time_zone, <span class="dt">origin =</span> <span class="st">&quot;1970-01-01&quot;</span>),</a>
<a class="sourceLine" id="cb3-14" title="14">   <span class="dt">user =</span> <span class="kw">map_chr</span>(twts_list, <span class="op">~</span><span class="kw">user2na</span>(.<span class="op">$</span>screenName)),</a>
<a class="sourceLine" id="cb3-15" title="15">   <span class="dt">rpto =</span> <span class="kw">map_chr</span>(twts_list, <span class="op">~</span><span class="kw">user2na</span>(.<span class="op">$</span>replyToSN)),</a>
<a class="sourceLine" id="cb3-16" title="16">   <span class="dt">text =</span> <span class="kw">map_chr</span>(twts_list, <span class="op">~</span>.<span class="op">$</span>text),</a>
<a class="sourceLine" id="cb3-17" title="17">   <span class="dt">lon  =</span> <span class="kw">map_dbl</span>(twts_list, <span class="op">~</span><span class="kw">coor2na</span>(.<span class="op">$</span>longitude)),</a>
<a class="sourceLine" id="cb3-18" title="18">   <span class="dt">lat  =</span> <span class="kw">map_dbl</span>(twts_list, <span class="op">~</span><span class="kw">coor2na</span>(.<span class="op">$</span>latitude)))</a>
<a class="sourceLine" id="cb3-19" title="19"></a>
<a class="sourceLine" id="cb3-20" title="20"><span class="kw">list2tbl</span>(wambra, <span class="st">&quot;EST&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">tail</span>(<span class="dv">3</span>)</a></code></pre></div>
<pre><code>## # A tibble: 3 x 9
##   isrt    rts  favs time                user   rpto   text             lon   lat
##   &lt;lgl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dttm&gt;              &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;          &lt;dbl&gt; &lt;dbl&gt;
## 1 FALSE    75    81 2020-01-08 22:17:37 @wamb~ @wamb~ &quot;#MuertesEnEl~    NA    NA
## 2 FALSE   626   578 2020-01-08 22:17:36 @wamb~ &lt;NA&gt;   &quot;[ESPECIAL]\n~    NA    NA
## 3 FALSE    10    17 2020-01-06 12:54:11 @wamb~ &lt;NA&gt;   &quot;[INTERNACION~    NA    NA</code></pre>
<p>Entre las publicaciones de dicho blog, llamo la atención a un artículo sobre las personas que lamentablemente fallecieron participando en las manifestaciones, o de manera paralela a las mismas.</p>
<blockquote class="twitter-tweet"><p lang="es" dir="ltr">[ESPECIAL]<br>Son 11 nombres, muy poco pronunciados en la historia del <a href="https://twitter.com/hashtag/ParoNacional?src=hash&amp;ref_src=twsrc%5Etfw">#ParoNacional</a> <a href="https://twitter.com/hashtag/Ecuador?src=hash&amp;ref_src=twsrc%5Etfw">#Ecuador</a><br><br>¿Quiénes eran las personas que murieron,<br>cómo ocurrió su muerte,<br>tiene responsabilidad la Fuerza Pública?<a href="https://twitter.com/hashtag/MuertesEnElParo?src=hash&amp;ref_src=twsrc%5Etfw">#MuertesEnElParo</a><br>8 historias<br>8 ilustraciones <br><br>Leer▶️ <a href="https://t.co/ln6WC7PzpI">https://t.co/ln6WC7PzpI</a> <a href="https://t.co/V474IiktKA">pic.twitter.com/V474IiktKA</a></p>&mdash; Wambra (@wambraEc) <a href="https://twitter.com/wambraEc/status/1215110345108467712?ref_src=twsrc%5Etfw">January 9, 2020</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<p>Una vez tabulados los metadatos, existe una variedad de aspectos que pueden ser analizados. La siguiente tabla presenta el conteo de <em>tweets</em> que contienen uno de tres <em>hashtags</em>, así como el porcentaje de los mismos que he considerado únicos (esto es, no son <em>replies</em> ni su texto se encuentra repetido), el conteo de usuarios y la razón promedio de <em>tweets</em> por usuario.</p>
<table>
<thead>
<tr class="header">
<th align="left">hashtag</th>
<th align="right">tweets (1)</th>
<th align="right">tweets únicos (2)</th>
<th align="right">porcentaje (2÷1)</th>
<th align="right">usuarios (3)</th>
<th align="right">razón (1÷3)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><a href="https://twitter.com/search?q=%23ParoNacionalEcuador%20until%3A2019-10-10%20since%3A2019-10-01">#ParoNacionalEcuador</a></td>
<td align="right">13770</td>
<td align="right">11471</td>
<td align="right">0.8330</td>
<td align="right">5297</td>
<td align="right">2.5996</td>
</tr>
<tr class="even">
<td align="left"><a href="https://twitter.com/search?q=%23EcuadorPaisDePaz%20until%3A2019-10-10%20since%3A2019-10-01">#EcuadorPaisDePaz</a></td>
<td align="right">19754</td>
<td align="right">13356</td>
<td align="right">0.6761</td>
<td align="right">5412</td>
<td align="right">3.6500</td>
</tr>
<tr class="odd">
<td align="left"><a href="https://twitter.com/search?q=%23ElParoSigue%20until%3A2019-10-10%20since%3A2019-10-01">#ElParoSigue</a></td>
<td align="right">13083</td>
<td align="right">10223</td>
<td align="right">0.7814</td>
<td align="right">3892</td>
<td align="right">3.3615</td>
</tr>
</tbody>
</table>
<p>Un par de ideas se derivan de este conteo. La inclusión de #EcuadorPaisDePaz se relaciona con un desprecio por las protestas, pero también se relaciona con el porcentaje más bajo de <em>tweets</em> únicos y la razón más alta de <em>tweets</em> por cuenta. Aunque los números no son atípicos, estas son las características del <em>spam</em>. En contraposición, el uso de #ParoNacionalEcuador demuestra el porcentaje más alto de publicaciones útiles, y la tasa más baja de contribución por usuario; este <em>hashtag</em> fue comúnmente utilizado para reportar con fotos y videos las situaciones violentas y la represión ejecutada por los aparatos del estado.</p>
<p>Además, al contar el uso por cuenta, se halló que solo tres cuentas superaron en 85 el uso de #ParoNacionalEcuador; una de ellas fue la de Pichincha Comunicaciones. Por el contrario, fueron catorce las cuentas que usaron #EcuadorPaisDePaz más de 85 veces, entre ellas: los ministerios de transporte y obras públicas, de desarrollo urbano y vivienda, y de salud pública; las secretarias técnica, del deporte, y de comunicación de la presidencia; el servicio de rentas internas y varias cuentas zonales del ministerio de inclusión económica y social. Este hecho confirma que se trata de propaganda mediática por parte de las instituciones públicas, para desmerecer las demandas de los sectores movilizados.</p>
<p>Los datos que alimentaron la tabla de conteo fueron obtenidos con tres ejecuciones de la siguiente función, variando cada vez el <em>hashtag</em> de interés. Notar el uso de un filtro que excluye los <em>retweets</em>, pues de otra manera los datos devueltos excederían el límite impuesto de veinte mil.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" title="1"><span class="kw">searchTwitter</span>(<span class="st">&quot;#ParoNacionalEcuador -filter:retweets&quot;</span>, <span class="fl">2e4</span>,</a>
<a class="sourceLine" id="cb5-2" title="2">              <span class="dt">since =</span> <span class="st">&quot;2019-10-01&quot;</span>, <span class="dt">until =</span> <span class="st">&quot;2019-10-10&quot;</span>)</a></code></pre></div>
<p>Desafortunadamente volver a ejecutar esta función no devolverá un solo <em>tweet</em>. Desconocía que la versión gratuita de la API solo recupera datos con una semana<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a> de antigüedad como máximo, a diferencia del sitio web que puede acceder a cualquier época. Es una lástima, pues no conservé los datos cuando ejecuté el análisis en octubre. Con todo existe <a href="https://github.com/Jefferson-Henrique/GetOldTweets-java">una</a> alternativa; básicamente, es un programa en java que simula la navegación en el sitio web de Twitter y recupera los datos conforme son presentados. Los siguientes comandos representan la obtención de <em>tweets</em> que contienen #ParoNacionalEcuador a través de la <em>command line</em>.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode bash"><code class="sourceCode bash"><a class="sourceLine" id="cb6-1" title="1"><span class="ex">PS</span> C:<span class="dt">\&gt;</span> git clone https://github.com/Jefferson-Henrique/GetOldTweets-java.git</a>
<a class="sourceLine" id="cb6-2" title="2"><span class="ex">PS</span> C:<span class="dt">\&gt;</span> cd GetOldTweets-java-master</a>
<a class="sourceLine" id="cb6-3" title="3"><span class="ex">PS</span> C:\GetOldTweets-java-master<span class="op">&gt;</span> java -jar got.jar querysearch=<span class="st">&quot;#ParoNacionalEC&quot;</span> since=2019-10-01 until=2019-10-15</a></code></pre></div>
<p>Los resultados son escritos en un archivo de valores separados por comas -punto y coma en realidad- para el cual escribí otra función, observando también que ocurría un uso inadecuado de las comillas:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" title="1">read.twts =<span class="st"> </span><span class="cf">function</span>(csv){</a>
<a class="sourceLine" id="cb7-2" title="2">   </a>
<a class="sourceLine" id="cb7-3" title="3">   lines =<span class="st"> </span><span class="kw">gsub</span>(<span class="st">&quot;</span><span class="ch">\&quot;</span><span class="st">;&quot;</span>, <span class="st">&quot;&#39;;&quot;</span>, <span class="kw">gsub</span>(<span class="st">&quot;;</span><span class="ch">\&quot;</span><span class="st">&quot;</span>, <span class="st">&quot;;&#39;&quot;</span>, <span class="kw">readLines</span>(csv)))</a>
<a class="sourceLine" id="cb7-4" title="4">   </a>
<a class="sourceLine" id="cb7-5" title="5">   cols =<span class="st"> </span><span class="kw">c</span>(<span class="dt">username =</span> <span class="st">&quot;NULL&quot;</span>, <span class="dt">date =</span> <span class="st">&quot;POSIXct&quot;</span>, <span class="dt">text =</span> <span class="st">&quot;character&quot;</span>, <span class="dt">geo =</span> <span class="st">&quot;NULL&quot;</span>)</a>
<a class="sourceLine" id="cb7-6" title="6">   </a>
<a class="sourceLine" id="cb7-7" title="7">   df =<span class="st"> </span><span class="kw">read.csv2</span>(<span class="dt">text =</span> lines, <span class="dt">colClasses =</span> cols, <span class="dt">na.strings =</span> <span class="st">&quot;&quot;</span>, <span class="dt">quote =</span> <span class="st">&quot;&#39;&quot;</span>)</a>
<a class="sourceLine" id="cb7-8" title="8">   </a>
<a class="sourceLine" id="cb7-9" title="9">   df<span class="op">$</span>user =<span class="st"> </span><span class="kw">gsub</span>(<span class="st">&quot;^https://twitter.com/(</span><span class="ch">\\</span><span class="st">w+)/status/</span><span class="ch">\\</span><span class="st">d+$&quot;</span>, <span class="st">&quot;@</span><span class="ch">\\</span><span class="st">1&quot;</span>, df<span class="op">$</span>permalink)</a>
<a class="sourceLine" id="cb7-10" title="10">   </a>
<a class="sourceLine" id="cb7-11" title="11">   df<span class="op">$</span>id =<span class="st"> </span><span class="kw">as.numeric</span>(df<span class="op">$</span>id)</a>
<a class="sourceLine" id="cb7-12" title="12">   </a>
<a class="sourceLine" id="cb7-13" title="13">   tibble<span class="op">::</span><span class="kw">as_tibble</span>(df)}</a></code></pre></div>
<p>Finalmente para leer los <em>tweets</em> recuperados: <code>read.twts("output_got.csv")</code></p>
<pre><code>## # A tibble: 244 x 9
##    date                retweets favorites text  mentions hashtags      id
##    &lt;dttm&gt;                 &lt;int&gt;     &lt;int&gt; &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;      &lt;dbl&gt;
##  1 2019-10-14 14:15:00      183       109 &quot;La ~ &lt;NA&gt;     #prensa~ 1.18e18
##  2 2019-10-13 21:43:00       84       133 &quot;#AT~ &lt;NA&gt;     #ATENCI~ 1.18e18
##  3 2019-10-13 20:11:00       47       111 &quot;Aqu~ &lt;NA&gt;     #SomosC~ 1.18e18
##  4 2019-10-13 17:30:00       66        66 &quot;#Lo~ &lt;NA&gt;     #LoQueN~ 1.18e18
##  5 2019-10-13 17:25:00      207       176 &quot;#Ur~ &lt;NA&gt;     #Urgent~ 1.18e18
##  6 2019-10-13 17:19:00       73        49 &quot;#UL~ @AnonsW~ #ULTIMO~ 1.18e18
##  7 2019-10-13 17:15:00      106        96 &quot;#Ah~ &lt;NA&gt;     #Ahora ~ 1.18e18
##  8 2019-10-13 17:14:00      228       238 &quot;Pes~ &lt;NA&gt;     #ParoNa~ 1.18e18
##  9 2019-10-13 16:57:00      312       242 &quot;Anu~ &lt;NA&gt;     #ParoNa~ 1.18e18
## 10 2019-10-13 16:17:00       65        62 &quot;Asi~ &lt;NA&gt;     #ParoNa~ 1.18e18
## # ... with 234 more rows, and 2 more variables: permalink &lt;chr&gt;, user &lt;chr&gt;</code></pre>
<p>En este caso se han recuperado solamente 244 de los 11471 <em>tweets</em> que originalmente se obtuvieron vía API. Es una cantidad mínima, pero es la alternativa a contratar un producto comercial de Twitter; a continuación, el desafío es averiguar hasta que nivel el análisis es replicable con esta cantidad reducida de datos.</p>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>A la fecha de publicación, el sitio web se encuentra suspendido debido a denuncias de la presidencia. De cualquier forma Pichincha Comunicaciones, al igual que las otras fuentes sugeridas, presenta en su Twitter la cobertura que realizó durante el paro.<a href="#fnref1" class="footnote-back">↩</a></p></li>
<li id="fn2"><p>La autenticación consiste en suministrar unas claves personales de consumidor y de acceso; para obtener esas claves uno debe poseer primero una cuenta de desarrollador.<a href="#fnref2" class="footnote-back">↩</a></p></li>
<li id="fn3"><p>El ejemplo con <em>tweets</em> de Wambra sí funciona porque utiliza una API diferente; una que accede a cualquier época, pero en una única cuenta. La búsqueda por <em>hashtag</em> o texto sí está restringida a una semana.<a href="#fnref3" class="footnote-back">↩</a></p></li>
</ol>
</div>

              
            </div>
          </div>
          <div id="post-footer" class="post-footer main-content-wrap">
            
              
                
                
                  <div class="post-footer-tags">
                    <span class="text-color-light text-small">Etiquetado en</span><br/>
                    
  <a class="tag tag--primary tag--small" href="../../../../tags/hashtags/">hashtags</a>

  <a class="tag tag--primary tag--small" href="../../../../tags/paro-nacional/">paro nacional</a>

                  </div>
                
              
            
            <div class="post-actions-wrap">
  
      <nav >
        <ul class="post-actions post-action-nav">
          
            <li class="post-action">
              
                <a class="post-action-btn btn btn--disabled">
              
                  <i class="fa fa-angle-left"></i>
                  <span class="hide-xs hide-sm text-small icon-ml">Siguiente</span>
                </a>
            </li>
            <li class="post-action">
              
                <a class="post-action-btn btn btn--default tooltip--top" href="../../../../post/2020/01/07-estimando-nodos-openstreetmap-pais/" data-tooltip="Estimando nodos OpenStreetMap por país">
              
                  <span class="hide-xs hide-sm text-small icon-mr">Anterior</span>
                  <i class="fa fa-angle-right"></i>
                </a>
            </li>
          
        </ul>
      </nav>
    <ul class="post-actions post-action-share" >
      
        <li class="post-action hide-lg hide-md hide-sm">
          <a class="post-action-btn btn btn--default btn-open-shareoptions" href="#btn-open-shareoptions">
            <i class="fa fa-share-alt"></i>
          </a>
        </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://twitter.com/intent/tweet?text=https://ruevko.github.io/hexagonal/post/2020/01/23-sobre-tweets-paro-nacional/">
              <i class="fab fa-twitter"></i>
            </a>
          </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://www.facebook.com/sharer/sharer.php?u=https://ruevko.github.io/hexagonal/post/2020/01/23-sobre-tweets-paro-nacional/">
              <i class="fab fa-facebook-f"></i>
            </a>
          </li>
        
      
      
      <li class="post-action">
        
          <a class="post-action-btn btn btn--default" href="#">
        
          <i class="fa fa-angle-double-up"></i>
        </a>
      </li>
    </ul>
  
</div>

            
              
            
          </div>
        </article>
        <footer id="footer" class="main-content-wrap">
  <span class="copyrights">
    &copy; 2020 <a href="https://github.com/ruevko">ruevko</a>. Todos los derechos reservados
  </span>
</footer>

      </div>
      <div id="bottom-bar" class="post-bottom-bar" data-behavior="4">
        <div class="post-actions-wrap">
  
      <nav >
        <ul class="post-actions post-action-nav">
          
            <li class="post-action">
              
                <a class="post-action-btn btn btn--disabled">
              
                  <i class="fa fa-angle-left"></i>
                  <span class="hide-xs hide-sm text-small icon-ml">Siguiente</span>
                </a>
            </li>
            <li class="post-action">
              
                <a class="post-action-btn btn btn--default tooltip--top" href="../../../../post/2020/01/07-estimando-nodos-openstreetmap-pais/" data-tooltip="Estimando nodos OpenStreetMap por país">
              
                  <span class="hide-xs hide-sm text-small icon-mr">Anterior</span>
                  <i class="fa fa-angle-right"></i>
                </a>
            </li>
          
        </ul>
      </nav>
    <ul class="post-actions post-action-share" >
      
        <li class="post-action hide-lg hide-md hide-sm">
          <a class="post-action-btn btn btn--default btn-open-shareoptions" href="#btn-open-shareoptions">
            <i class="fa fa-share-alt"></i>
          </a>
        </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://twitter.com/intent/tweet?text=https://ruevko.github.io/hexagonal/post/2020/01/23-sobre-tweets-paro-nacional/">
              <i class="fab fa-twitter"></i>
            </a>
          </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://www.facebook.com/sharer/sharer.php?u=https://ruevko.github.io/hexagonal/post/2020/01/23-sobre-tweets-paro-nacional/">
              <i class="fab fa-facebook-f"></i>
            </a>
          </li>
        
      
      
      <li class="post-action">
        
          <a class="post-action-btn btn btn--default" href="#">
        
          <i class="fa fa-angle-double-up"></i>
        </a>
      </li>
    </ul>
  
</div>

      </div>
      <div id="share-options-bar" class="share-options-bar" data-behavior="4">
  <i id="btn-close-shareoptions" class="fa fa-close"></i>
  <ul class="share-options">
    
      <li class="share-option">
        <a class="share-option-btn" target="new" href="https://twitter.com/intent/tweet?text=https%3A%2F%2Fruevko.github.io%2Fhexagonal%2Fpost%2F2020%2F01%2F23-sobre-tweets-paro-nacional%2F">
          <i class="fab fa-twitter"></i><span>Compartir en Twitter</span>
        </a>
      </li>
    
      <li class="share-option">
        <a class="share-option-btn" target="new" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fruevko.github.io%2Fhexagonal%2Fpost%2F2020%2F01%2F23-sobre-tweets-paro-nacional%2F">
          <i class="fab fa-facebook-f"></i><span>Compartir en Facebook</span>
        </a>
      </li>
    
  </ul>
</div>
<div id="share-options-mask" class="share-options-mask"></div>

    </div>
    
    <div id="about">
  <div id="about-card">
    <div id="about-btn-close">
      <i class="fas fa-times"></i>
    </div>
    
      <img id="about-card-picture" src="https://ruevko.github.io/hexagonal/logo.png" alt="Foto de autor" />
    
    <h4 id="about-card-name">La Galería Hexagonal</h4>
    
      <div id="about-card-bio">Este blog llega a ustedes cortesía de Rafael Castro, saludos :kissing_heart:</div>
    
    
      <div id="about-card-job">
        <i class="fas fa-graduation-cap"></i>
        <br/>
        Geógrafo
      </div>
    
    
      <div id="about-card-location">
        <i class="fas fa-home"></i>
        <br/>
        Ecuador
      </div>
    
  </div>
</div>

    

    
  
    <div id="cover" style="background-image:url('https://res.cloudinary.com/dodnzqhiz/image/upload/v1577918037/crv.png');"></div>
  


    
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.7/js/jquery.fancybox.min.js" integrity="sha256-GEAnjcTqVP+vBp3SSc8bEDQqvWAZMiHyUSIorrWwH50=" crossorigin="anonymous"></script>


<script src="../../../../js/script-pcw6v3xilnxydl1vddzazdverrnn9ctynvnxgwho987mfyqkuylcb1nlt.min.js"></script>


<script lang="javascript">
window.onload = updateMinWidth;
window.onresize = updateMinWidth;
document.getElementById("sidebar").addEventListener("transitionend", updateMinWidth);
function updateMinWidth() {
  var sidebar = document.getElementById("sidebar");
  var main = document.getElementById("main");
  main.style.minWidth = "";
  var w1 = getComputedStyle(main).getPropertyValue("min-width");
  var w2 = getComputedStyle(sidebar).getPropertyValue("width");
  var w3 = getComputedStyle(sidebar).getPropertyValue("left");
  main.style.minWidth = `calc(${w1} - ${w2} - ${w3})`;
}
</script>


  
    
  




    
  </body>
</html>

