# Tranquilpeak
# Version : 0.4.8-BETA
# Author : Thibaud Leprêtre

ignoreFiles = ["\\.csv$", "\\.sh.$", "\\.txt$", "\\.RDS$", "\\.Rmd$", "_cache$", "_files$"]
ignoreErrors = ["error-output-taxonomy"]
baseURL = "https://ruevko.github.io/hexagonal/"
title = "La Galería Hexagonal"
defaultContentLanguage = "es"
theme = "tranquilpeak"
publishDir = "docs"
canonifyURLs = true
relativeURLs = true
enableEmoji = true
paginate = 6

[author]
  name = "Roger Rafael Castro Zambrano"
  picture = "logo.png"
  location = "Ecuador"
  job = "Geógrafo"

[outputs]
  section = "HTML"
  taxonomy = "HTML"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[languages]

  [languages.es]
    weight = 1
    languageName = "Español"

[menus]

  [[menu.main]]
    weight = 1
    identifier = "archives"
    name = "Archives"
    pre = "fas fa-globe-americas" #fa-globe
    url = "/archives"
  [[menu.main]]
    weight = 2
    identifier = "categories"
    name = "Categories"
    pre = "fas fa-map-marked-alt" #fa-map
    url = "/categories"
  [[menu.main]]
    weight = 3
    identifier = "tags"
    name = "Tags"
    pre = "fas fa-map-marker-alt"
    url = "/tags"
  #[[menu.main]]
    #weight = 4
    #identifier = "rss"
    #name = "RSS"
    #pre = "fas fa-atlas"
    #url = "/index.xml"

  [[menu.links]]
    weight = 1
    identifier = "github"
    name = "GitHub"
    pre = "fab fa-github-alt"
    url = "https://github.com/ruevko"
  [[menu.links]]
    weight = 2
    identifier = "twitter"
    name = "Twitter"
    pre = "fab fa-twitter"
    url = "https://twitter.com/ruevko"
  [[menu.links]]
    weight = 3
    identifier = "kofi"
    name = "Ko-fi"
    pre = "fas fa-coffee"
    url = "https://ko-fi.com/ruevko"
  #[[menu.links]]
    #weight = 4
    #identifier = "rbloggers"
    #name = "R-bloggers"
    #pre = "fas fa-rss"
    #url = "https://www.r-bloggers.com"

[params]

  favicon = "favicon.png"
  dateFormat = "2 de January de 2006"
  keywords = ["análisis", "cartografía", "datos", "mapas"]
  description = "El blog de Rafael Castro, orientado a Cartografía y Análisis de Datos"
  coverImage = "https://res.cloudinary.com/dodnzqhiz/image/upload/v1577918037/crv.png"
  sharingMessage = "Este artículo fue publicado en el blog La Galería Hexagonal"
  thumbnailImagePosition = "right"
  hierarchicalCategories = false
  autoThumbnailImage = true
  thumbnailImage = true
  imageGallery = false
  clearReading = true
  sidebarBehavior = 1

[params.sharing]

  [[params.sharingOptions]]
    name = "Facebook"
    icon = "fab fa-facebook"
    url = "https://www.facebook.com/sharer.php?t=%s&u=%s"
  [[params.sharingOptions]]
    name = "Twitter"
    icon = "fab fa-twitter"
    url = "https://twitter.com/intent/tweet?text=%s&url=%s"
  [[params.sharingOptions]]
    name = "GitHub"
    icon = "fab fa-github-alt"
    url = "https://github.com/ruevko/hexagonal/blob/master/content/%s%s"
  [[params.sharingOptions]]
    name = "Telegram"
    icon = "fab fa-telegram-plane"
    url = "https://t.me/share/url?text=%s&url=%s"
  [[params.sharingOptions]]
    name = "WhatsApp"
    icon = "fab fa-whatsapp"
    url = "https://api.whatsapp.com/send?text=%s %s"

[params.miscellaneous]

  #[[params.miscellaneousMenu]]
    #name = "Suscripción"
    #icon = "fas fa-envelope"
    #url = "https://follow.it/ruevko"
  [[params.miscellaneousMenu]]
    name = "Acerca de . . ."
    icon = "fas fa-compass"
    url = "/post/readme"
  #[[params.miscellaneousMenu]]
    #name = "The english blog . . ."
    #icon = "fas fa-map-signs"
    #url = "en"

[params.header]
  #icon = "fas fa-map-signs"
  icon = "fas fa-chevron-down"
  url = "#footer"

[params.footer]
  copyright = "by Rafael Castro <i class=\"fas fa-lg fa-crow\"></i>"
