# Tranquilpeak
# Version : 0.4.8-BETA
# Author : Thibaud Leprêtre

ignoreFiles = ["\\.csv$", "\\.sh.$", "\\.RDS$", "\\.Rmd$", "_files$", "_cache$"]
ignoreErrors = ["error-output-taxonomy"]
baseURL = "https://ruevko.github.io/hexagonal/"
theme = "hugo-tranquilpeak-theme"
defaultContentLanguage = "es-es"
title = "La Galería Hexagonal"
publishDir = "docs"
canonifyURLs = true
relativeURLs = true
enableEmoji = true
paginate = 6

[author]
  name = "Roger Rafael Castro Zambrano"
  picture = "/hexagonal/logo.png"
  location = "Ecuador"
  job = "Geógrafo"

[outputs]
  section = "HTML"
  taxonomy = "HTML"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[languages]

  [languages.es-es]
    weight = 1
    languageName = "Español"

[menus]

  #[[menu.main]]
    #weight = 1
    #identifier = "home"
    #name = "Home"
    #pre = "fas fa-atlas"
    #url = "/"
  [[menu.main]]
    weight = 2
    identifier = "archives"
    name = "Archives"
    pre = "fas fa-globe-americas" #fa-globe
    url = "/archives"
  [[menu.main]]
    weight = 3
    identifier = "categories"
    name = "Categories"
    pre = "fas fa-map-marked-alt" #fa-map
    url = "/categories"
  [[menu.main]]
    weight = 4
    identifier = "tags"
    name = "Tags"
    pre = "fas fa-map-marker-alt"
    url = "/tags"

  [[menu.links]]
    weight = 2
    identifier = "github"
    name = "GitHub"
    pre = "fab fa-github-alt"
    url = "https://github.com/ruevko"
  [[menu.links]]
    weight = 3
    identifier = "twitter"
    name = "Twitter"
    pre = "fab fa-twitter"
    url = "https://twitter.com/ruevko"
  [[menu.links]]
    weight = 4
    identifier = "kofi"
    name = "Ko-fi"
    pre = "fas fa-coffee"
    url = "https://ko-fi.com/ruevko"
  #[[menu.links]]
    #weight = 1
    #identifier = "researchgate"
    #name = "RGate"
    #pre = "fab fa-researchgate"
    #url = "https://www.researchgate.net/profile/Roger_Rafael_Castro_Zambrano"

  [[menu.misc]]
    weight = 5
    identifier = "readme"
    name = "Acerca de..."
    pre = "fas fa-compass"
    url = "/post/readme"
  #[[menu.misc]]
    #weight = 6
    #identifier = "english"
    #name = "English blog..."
    #pre = "fas fa-map-signs"
    #url = "/post/readme"

[params]

  favicon = "/favicon.png"
  dateFormat = "2 de January de 2006"
  keywords = ["análisis", "cartografía", "datos", "mapas"]
  description = "El blog de Rafael Castro, orientado a Cartografía y Análisis de Datos"
  coverImage = "https://res.cloudinary.com/dodnzqhiz/image/upload/v1577918037/crv.png"
  sharingMessage = "Este artículo fue publicado en el blog La Galería Hexagonal"
  thumbnailImagePosition = "right"
  hierarchicalCategories = false
  autoThumbnailImage = true
  thumbnailImage = true
  imageGallery = false
  clearReading = true
  sidebarBehavior = 1

  [[params.sharingOptions]]
    name = "Compartir en Facebook"
    icon = "fab fa-facebook"
    url = "https://www.facebook.com/sharer.php?t=%s&u=%s"

  [[params.sharingOptions]]
    name = "Compartir en Twitter"
    icon = "fab fa-twitter"
    url = "https://twitter.com/intent/tweet?text=%s&url=%s"

  [[params.sharingOptions]]
    name = "Ver código en Github"
    icon = "fab fa-github-alt"
    url = "https://github.com/ruevko/hexagonal/blob/master/content/%s%s.Rmd"

  [[params.sharingOptions]]
    name = "Enviar con Telegram"
    icon = "fab fa-telegram-plane"
    url = "https://t.me/share/url?text=%s&url=%s"

  [[params.sharingOptions]]
    name = "Enviar con WhatsApp"
    icon = "fab fa-whatsapp"
    url = "https://api.whatsapp.com/send?text=%s %s"

[params.header.rightLink]
  icon = "chevron-down"
  url = "#footer"

[params.footer]
  copyright = "by Rafael Castro <i class=\"fas fa-lg fa-crow\"></i>"
