# Tranquilpeak
# Version : 0.4.8-BETA
# Author : Thibaud Leprêtre

ignoreFiles = ["\\.csv$", "\\.shp$", "\\.shx$", "\\.RDS$", "\\.Rmd$", "_files$", "_cache$"]

publishDir = "docs"
title = "La Galería Hexagonal"
baseURL = "https://ruevko.github.io/hexagonal/"
theme = "hugo-tranquilpeak-theme"
defaultContentLanguage = "es-es"
languageCode = "es-es"
relativeURLs = true
canonifyurls = true
enableEmoji = true
paginate = 6

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Roger Rafael Castro Zambrano"
  picture = "/hexagonal/logo.png"
  location = "Ecuador"
  job = "Geógrafo"
  bio = "El blog de Rafael Castro, orientado a Cartografía y Análisis de Datos"

  #[[menu.main]]
    #weight = 1
    #identifier = "home"
    #name = "Home"
    #pre = "<i class=\"sidebar-button-icon fas fa-lg fa-atlas\"></i>"
    #url = "/"
  [[menu.main]]
    weight = 2
    identifier = "archives"
    name = "Archives"
    pre = "<i class=\"sidebar-button-icon fas fa-lg fa-globe-americas\"></i>" #fa-globe
    url = "/archives"
  [[menu.main]]
    weight = 3
    identifier = "categories"
    name = "Categories"
    pre = "<i class=\"sidebar-button-icon fas fa-lg fa-map-marked-alt\"></i>" #fa-map
    url = "/categories"
  [[menu.main]]
    weight = 4
    identifier = "tags"
    name = "Tags"
    pre = "<i class=\"sidebar-button-icon fas fa-lg fa-map-marker-alt\"></i>"
    url = "/tags"

  [[menu.links]]
    weight = 2
    identifier = "github"
    name = "GitHub"
    pre = "<i class=\"sidebar-button-icon fab fa-lg fa-github-alt\"></i>"
    url = "https://github.com/ruevko"
  [[menu.links]]
    weight = 3
    identifier = "twitter"
    name = "Twitter"
    pre = "<i class=\"sidebar-button-icon fab fa-lg fa-twitter\"></i>"
    url = "https://twitter.com/ruevko"
  [[menu.links]]
    weight = 4
    identifier = "kofi"
    name = "Ko-fi"
    pre = "<i class=\"sidebar-button-icon fas fa-lg fa-coffee\"></i>"
    url = "https://ko-fi.com/ruevko"
  #[[menu.links]]
    #weight = 1
    #identifier = "researchgate"
    #name = "RGate"
    #pre = "<i class=\"sidebar-button-icon fab fa-lg fa-researchgate\"></i>"
    #url = "https://www.researchgate.net/profile/Roger_Rafael_Castro_Zambrano"
  #[[menu.links]]
    #weight = 5
    #identifier = "linkedin"
    #name = "LinkedIn"
    #pre = "<i class=\"sidebar-button-icon fab fa-lg fa-linkedin\"></i>"
    #url = "https://www.linkedin.com/in/roger-rafael-castro-zambrano-143738188"
  #[[menu.links]]
    #weight = 6
    #identifier = "instagram"
    #name = "Instagram"
    #pre = "<i class=\"sidebar-button-icon fab fa-lg fa-instagram\"></i>"
    #url = "https://instagram.com/ruevko"

  [[menu.misc]]
    weight = 5
    identifier = "readme"
    name = "Acerca de..."
    pre = "<i class=\"sidebar-button-icon fas fa-lg fa-compass\"></i>"
    url = "/post/readme"
  #[[menu.misc]]
    #weight = 6
    #identifier = "english"
    #name = "English blog..."
    #pre = "<i class=\"sidebar-button-icon fas fa-lg fa-map-signs\"></i>"
    #url = "/post/readme"

[params]

  favicon = "/favicon.png"
  dateFormat = "2 de January de 2006"
  keywords = ["análisis", "cartografía", "datos", "mapas"]
  description = "El blog de Rafael Castro, orientado a Cartografía y Análisis de Datos"
  coverImage = "https://res.cloudinary.com/dodnzqhiz/image/upload/v1577918037/crv.png"
  thumbnailImagePosition = "right"
  thumbnailImage = true
  autoThumbnailImage = true
  hierarchicalCategories = false
  imageGallery = false
  clearReading = true
  sidebarBehavior = 1

  [[params.sharingOptions]]
    name = "Twitter"
    icon = "fa-twitter"
    url = "https://twitter.com/intent/tweet?text=%s"

  [[params.sharingOptions]]
    name = "Facebook"
    icon = "fa-facebook"
    url = "https://www.facebook.com/sharer/sharer.php?u=%s"

[params.header.rightLink]
  icon = "chevron-down"
  url = "#footer"

[params.footer]
  copyright = "by Rafael Castro <i class=\"fas fa-lg fa-crow\"></i>"
#"<br><a href=\"https://ko-fi.com/A0A61KV0W\"></a> <i class=\"fas fa-lg fa-coffee\"></i>"
