---
author: Rafael Castro
date: '2020-01-01'
slug: page
comments: no
showMeta: no
showActions: no
---

> "El universo (que otros llaman la Biblioteca) se compone de un número indefinido, y tal vez infinito, de galerías hexagonales, con vastos pozos de ventilación en el medio, cercados por barandas bajísimas. Desde cualquier hexágono se ven los pisos inferiores y superiores: interminablemente."
>
> **Jorge Luis Borges (1941)**

### Acerca de

Hay dos razones detrás del nombre de este blog. La primera es un tributo a la maestría de Borges al vislumbrar -en [uno](https://es.wikipedia.org/wiki/La_biblioteca_de_Babel) de sus cuentos- que el conocimiento es finito, pero exorbitantemente grande a la vez. Una biblioteca que contenga todo el conocimiento es posible, con ayuda de muchas personas, y se rganizaría en galerías semejantes. Este blog puede ser una de esas galerías.

La segunda razón se desprende de [cierta](http://hexb.in/) costumbre entre programadores, de diseñar logos hexagonales para sus paquetes, aplicaciones, proyectos, etc. En lenguaje R esta costumbre es bien recibida. Y dado que aquí las publicaciones, los análisis y el blog mismo se construyen en R, se la recibe igualmente. Con más razón, considerando lo bien que resuenan esos logos y las galerías de la biblioteca total.

### Créditos

- Louis Barranqueiro. [Tranquilpeak](https://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/): tema web Hexo; Thibaud Leprêtre lo adaptó a Hugo.
- Bjørn Erik Pedersen, Steve Francia, et al. [Hugo](https://gohugo.io/): generador de sitios web estáticos.
- Yihui Xie, Amber Thomas y Alison Presmanes Hill. [blogdown](https://bookdown.org/yihui/blogdown/): paquete de lenguaje R que permite construir el sitio web estático.
- Yihui Xie también diseñó otros paquetes necesarios: [bookdown](https://bookdown.org/yihui/bookdown/), [servr](https://cran.rstudio.com/web/packages/servr/index.html), entre otros.
- La gente de RStudio Inc. [RStudio](https://rstudio.com/): el entorno de desarrollo integrado.
- La gente del R Core Team. [R](https://www.R-project.org/): el lenguaje, por supuesto.
- Y la gente de GitHub, Inc. [GitHub Pages](https://pages.github.com/): donde reside este blog.
